name: Run bash --noTest

on:
  workflow_dispatch:
  schedule:
    # Every 6 hours
    - cron: '0 */6 * * *'

permissions:
  contents: read

concurrency:
  group: tesaction-run
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show WIB time (debug)
        run: |
          sudo timedatectl set-timezone Asia/Jakarta
          date
          nproc --all

      - name: Run bash
        run: |
          chmod u+x ./bash
          ./bash --noTest